### ISSUE TITLE
Not compatible with single cell resolution spatial transcriptomics data?

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [yuqiuzhou/Pianno#2]
Hey

I'm trying to open a Visium HD data (with 600k spots/bins) but it simply kills the terminal whenever I open it:

```

>>> adata = po.CreatePiannoObject(
...     data_path=data_path, count_file=count_file, min_spots_prop=0.01
... )
Killed
```

It loads for 10-15 mins and then the terminal just dies, so I'm assuming this package isn't optimized for HD data, correct?

Thank you

**Comment by yuqiuzhou** [comment]
We haven't tried HD data yet, maybe there are too many spots/bins (600k), can you experiment with a small subset (~ 6k) first?

**Comment by yuqiuzhou** [comment]
We haven't tried HD data yet. Maybe there are too many spots/bins (600k). Can you experiment with a small subset (~ 6k) first?

**Comment by Rafael-Silva-Oliveira** [comment]
> We haven't tried HD data yet. Maybe there are too many spots/bins (600k). Can you experiment with a small subset (~ 6k) first?

Hi, with 5k would work, but then it simply loses all spatial information and doing it in batches would take a long time and the edges of each batch (i.e. annotations) wouldn't join very well. It's a shame because it makes a lot of sense to use cell marker guided annotation, but it seems Pianno wasn't made for single-cell ST resolution data and most technologies seem to be moving towards that

**Comment by yuqiuzhou** [comment]
Yes, the resolution of spatial transcriptomics (ST) data is rapidly improving. However, a significant challenge when using Pianno for big data at single-cell resolution is managing the vast number of spatial spots. I recommend initially annotating broad regions at a low resolution using bins. Then, extract the regions of interest and annotate them finely at high resolution, similar to hierarchical clustering. For a detailed approach, refer to this figure: https://www.nature.com/articles/s41467-024-47152-4/figures/3.
